# Find the k8s image from https://console.cloud.google.com/gcr/images/google-containers/GLOBAL
FROM gcr.io/google-containers/etcd-amd64@sha256:b960569ade5f37205a033dcdc3191fe99dc95b15c6795a6282859070ec2c6124
MAINTAINER steven.zhangyong@outlook.com



